# CSS 检测器
plugins:
  - stylelint-scss
  - stylelint-order
extends:
  # 如果你使用 Prettier 和 Stylelint，你应该使用他们的 SCSS 共享配置：
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue/scss
  - stylelint-config-prettier-scss
  - stylelint-config-recommended-vue
  - stylelint-config-idiomatic-order
overrides:
  - files:
      - '*.vue'
      - '**/*.vue'
    rules: { unit-allowed-list: [em, rem, px, s, %, vh, deg] }
rules:
  selector-class-pattern:
    ['^([a-z][_a-z--0-9__]*)(-[_a-z--0-9__]+)*$', { 'message': 'Expected class selector to be kebab-case' }]
  scss/dollar-variable-pattern: ^\$_?[a-z]+[\\w-]*$
  at-rule-empty-line-before: [always, { ignoreAtRules: [else] }]
  block-opening-brace-space-before: always
  block-closing-brace-newline-after: [always, { ignoreAtRules: [if else] }]
  at-rule-name-space-after: always
  rule-empty-line-before: always
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate
